name: matterbridge
version: "v1.26.0"
summary: MatterBridge protocol bridge
base: core20
description: |
  bridge between mattermost, IRC, gitter, xmpp, slack, discord, telegram,
  rocket.chat, hipchat (via xmpp), steam and matrix with REST API

grade: stable
confinement: strict

apps:
  matterbridge:
    command: bin/matterbridge -conf $SNAP_COMMON/matterbridge.toml
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  matterbridge:
    plugin: go
    build-packages:
      - gcc
    source: https://github.com/42wim/matterbridge.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags `git rev-list --tags --max-count=1`)"
      last_committed_tag_ver="$(echo $last_committed_tag)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
