name: matterbridge
version: "v1.26.0"
summary: MatterBridge protocol bridge
base: core24
license: Apache-2.0
contact: https://github.com/popey/matterbridge-snap/issues
issues: https://github.com/popey/matterbridge-snap/issues
source-code: https://github.com/popey/matterbridge-snap
website: https://github.com/42wim/matterbridge
description: |
  Bridge between mattermost, IRC, gitter, xmpp, slack, discord, telegram,
  rocket.chat, hipchat (via xmpp), steam and matrix with REST API.

  After installing, copy your configuration file to:

    /var/snap/matterbridge/common/matterbridge.toml

  The service will start automatically. Check logs with:

    snap logs matterbridge

  See https://github.com/42wim/matterbridge/wiki for configuration help.

  This snap is maintained by Alan Pope, and is not
  necessarily endorsed or officially maintained by the upstream developers.

platforms:
  amd64:
  arm64:

grade: stable
confinement: strict

apps:
  matterbridge:
    command: bin/matterbridge -conf $SNAP_COMMON/matterbridge.toml
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind

parts:
  matterbridge:
    plugin: go
    build-snaps:
      - go/latest/stable
    build-packages:
      - gcc
    source: https://github.com/42wim/matterbridge.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
