name: matterbridge
adopt-info: matterbridge
summary: MatterBridge protocol bridge
base: core18
description: |
  bridge between mattermost, IRC, gitter, xmpp, slack, discord, telegram,
  rocket.chat, hipchat (via xmpp), steam and matrix with REST API

grade: stable
confinement: strict

apps:
  matterbridge:
    command: matterbridge
    plugs:
      - network
      - network-bind

parts:
  build-trigger:
    plugin: nil
    source: https://github.com/42wim/matterbridge.git
  matterbridge:
    plugin: go
    build-packages:
      - gcc
    go-channel: 1.13/stable
    source: git://github.com/42wim/matterbridge.git
    go-importpath: github.com/42wim/matterbridge
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags `git rev-list --tags --max-count=1`)"
      last_committed_tag_ver="$(echo $last_committed_tag | tr -d 'v')"
      last_released_tag="$(snap info matterbridge | awk '$1 == "beta:" { print $2 }' | tr -d 'v')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "${last_committed_tag_ver}"
